/*
 * Copyright 2014, NICTA
 *
 * This software may be distributed and modified according to the terms of
 * the BSD 2-Clause license. Note that NO WARRANTY is provided.
 * See "LICENSE_BSD2.txt" for details.
 *
 * @TAG(NICTA_BSD)
 */

/*
 * timer.h
 *
 *  Created on: Aug 1, 2013
 *      Author: jxie
 */

#ifndef TIMER_H_
#define TIMER_H_


#define DIV_1		0
#define DIV_2		1
#define DIV_4		2
#define DIV_8		3
#define DIV_16		4


	/***************************/
	/* PWM Timer Registers     */
	/***************************/
struct pwm_timer{
	volatile uint32_t TCFG0;
	volatile uint32_t TCFG1;
	volatile uint32_t TCON;
	volatile uint32_t TCNTB0;
	volatile uint32_t TCMPB0;
	volatile uint32_t TCNTO0;
	volatile uint32_t TCNTB1;
	volatile uint32_t TCMPB1;
	volatile uint32_t TCNTO1;
	volatile uint32_t TCNTB2;
	volatile uint32_t TCMPB2;
	volatile uint32_t TCNTO2;
	volatile uint32_t TCNTB3;
	volatile uint32_t TCMPB3;
	volatile uint32_t TCNTO3;
	volatile uint32_t TCNTB4;
	volatile uint32_t TCNTO4;
	volatile uint32_t TINT_CSTAT;
};

/* TCFG0 */
#define TIMER_TCFG0_DEAD_ZONE_LENGTH_SHIFT		16
#define TIMER_TCFG0_DEAD_ZONE_LENGTH_MASK		(0xff << TIMER_TCFG0_DEAD_ZONE_LENGTH_SHIFT)
#define TIMER_TCFG0_PRESCALER_1_SHIFT			8
#define TIMER_TCFG0_PRESCALER_1_MASK			(0xff << TIMER_TCFG0_PRESCALER_1_SHIFT)
#define TIMER_TCFG0_PRESCALER_0_SHIFT			0
#define TIMER_TCFG0_PRESCALER_0_MASK			(0xff << TIMER_TCFG0_PRESCALER_0_SHIFT)
/* TCFG1 */
#define TIMER_TCFG1_DIV_MUX4_SHIFT				16
#define TIMER_TCFG1_DIV_MUX4_MASK				(0xf << TIMER_TCFG1_DIV_MUX4_SHIFT)
#define TIMER_TCFG1_DIV_MUX3_SHIFT				12
#define TIMER_TCFG1_DIV_MUX3_MASK				(0xf << TIMER_TCFG1_DIV_MUX3_SHIFT)
#define TIMER_TCFG1_DIV_MUX2_SHIFT				8
#define	TIMER_TCFG1_DIV_MUX2_MASK				(0xf << TIMER_TCFG1_DIV_MUX2_SHIFT)
#define TIMER_TCFG1_DIV_MUX1_SHIFT				4
#define TIMER_TCFG1_DIV_MUX1_MASK				(0xf << TIMER_TCFG1_DIV_MUX1_SHIFT)
#define TIMER_TCFG1_DIV_MUX0_SHIFT				0
#define TIMER_TCFG1_DIV_MUX0_MASK				(0xf << TIMER_TCFG1_DIV_MUX0_SHIFT)
/* TCON */
#define TIMER_TCON_TIMER4_AUTO_RELOAD_SHIFT		22
#define TIMER_TCON_TIMER4_AUTO_RELOAD_MASK		(1 << TIMER_TCON_TIMER4_AUTO_RELOAD_SHIFT)
#define TIMER_TCON_TIMER4_MANUAL_UPDATE_SHIFT	21
#define TIMER_TCON_TIMER4_MANUAL_UPDATE_MASK	(1 << TIMER_TCON_TIMER4_MANUAL_UPDATE_SHIFT)
#define TIMER_TCON_TIMER4_START_STOP_SHIFT		20
#define TIMER_TCON_TIMER4_START_STOP_MASK		(1 << TIMER_TCON_TIMER4_START_STOP_SHIFT)

#define TIMER_TCON_TIMER3_AUTO_RELOAD_SHIFT		19
#define TIMER_TCON_TIMER3_AUTO_RELOAD_MASK		(1 << TIMER_TCON_TIMER3_AUTO_RELOAD_SHIFT)
#define TIMER_TCON_TIMER3_OUTPUT_INVERT_SHIFT	18
#define TIMER_TCON_TIMER3_OUTPUT_INVERT_MASK	(1 << TIMER_TCON_TIMER3_OUTPUT_INVERT_SHIFT)
#define TIMER_TCON_TIMER3_MANUAL_UPDATE_SHIFT	17
#define TIMER_TCON_TIMER3_MANUAL_UPDATE_MASK	(1 << TIMER_TCON_TIMER3_MANUAL_UPDATE_SHIFT)
#define TIMER_TCON_TIMER3_START_STOP_SHIFT		16
#define TIMER_TCON_TIMER3_START_STOP_MASK		(1 << TIMER_TCON_TIMER3_START_STOP_SHIFT)


#define TIMER_TCON_TIMER2_AUTO_RELOAD_SHIFT		15
#define TIMER_TCON_TIMER2_OUTPUT_INVERT_SHIFT	14
#define TIMER_TCON_TIMER2_MANUAL_UPDATE_SHIFT	13
#define TIMER_TCON_TIMER2_START_STOP_SHIFT		12
#define TIMER_TCON_TIMER2_AUTO_RELOAD_MASK		(1 << TIMER_TCON_TIMER2_AUTO_RELOAD_SHIFT)
#define TIMER_TCON_TIMER2_OUTPUT_INVERT_MASK	(1 << TIMER_TCON_TIMER2_OUTPUT_INVERT_SHIFT)
#define TIMER_TCON_TIMER2_MANUAL_UPDATE_MASK	(1 << TIMER_TCON_TIMER2_MANUAL_UPDATE_SHIFT)
#define TIMER_TCON_TIMER2_START_STOP_MASK		(1 << TIMER_TCON_TIMER2_START_STOP_SHIFT)


#define TIMER_TCON_TIMER1_AUTO_RELOAD_SHIFT		11
#define TIMER_TCON_TIMER1_OUTPUT_INVERT_SHIFT	10
#define TIMER_TCON_TIMER1_MANUAL_UPDATE_SHIFT	9
#define TIMER_TCON_TIMER1_START_STOP_SHIFT		8
#define TIMER_TCON_TIMER1_AUTO_RELOAD_MASK		(1 << TIMER_TCON_TIMER1_AUTO_RELOAD_SHIFT)
#define TIMER_TCON_TIMER1_OUTPUT_INVERT_MASK	(1 << TIMER_TCON_TIMER1_OUTPUT_INVERT_SHIFT)
#define TIMER_TCON_TIMER1_MANUAL_UPDATE_MASK	(1 << TIMER_TCON_TIMER1_MANUAL_UPDATE_SHIFT)
#define TIMER_TCON_TIMER1_START_STOP_MASK		(1 << TIMER_TCON_TIMER1_START_STOP_SHIFT)

#define TIMER_TCON_DEAD_ZONE_SHIFT				4
#define TIMER_TCON_DEAD_ZONE_MASK				(1 << TIMER_TCON_DEAD_ZONE_SHIFT)

#define TIMER_TCON_TIMER0_AUTO_RELOAD_SHIFT		3
#define TIMER_TCON_TIMER0_OUTPUT_INVERT_SHIFT	2
#define TIMER_TCON_TIMER0_MANUAL_UPDATE_SHIFT	1
#define TIMER_TCON_TIMER0_START_STOP_SHIFT		0
#define TIMER_TCON_TIMER0_AUTO_RELOAD_MASK		(1 << TIMER_TCON_TIMER0_AUTO_RELOAD_SHIFT)
#define TIMER_TCON_TIMER0_OUTPUT_INVERT_MASK	(1 << TIMER_TCON_TIMER0_OUTPUT_INVERT_SHIFT)
#define TIMER_TCON_TIMER0_MANUAL_UPDATE_MASK	(1 << TIMER_TCON_TIMER0_MANUAL_UPDATE_SHIFT)
#define TIMER_TCON_TIMER0_START_STOP_MASK		(1 << TIMER_TCON_TIMER0_START_STOP_SHIFT)



/* TCNTB0: TImer 0 count buffer */
/* TCMPB0: TImer 0 compare buffer */
/* TCNTO0: TImer 0 count observation */
/* TCNTB1: TImer 1 count buffer */
/* TCMPB1: TImer 1 compare buffer */
/* TCNTO1: TImer 1 count observation */

#define TIMER_TIMER4_INIT_STS_SHIFT		9
#define TIMER_TIMER3_INIT_STS_SHIFT		8
#define TIMER_TIMER2_INIT_STS_SHIFT		7
#define TIMER_TIMER1_INIT_STS_SHIFT		6
#define TIMER_TIMER0_INIT_STS_SHIFT		5

#define TIMER_TIMER4_INIT_STS_MASK		(1 << TIMER_TIMER4_INIT_STS_SHIFT)
#define TIMER_TIMER3_INIT_STS_MASK		(1 << TIMER_TIMER3_INIT_STS_SHIFT)
#define TIMER_TIMER2_INIT_STS_MASK		(1 << TIMER_TIMER2_INIT_STS_SHIFT)
#define TIMER_TIMER1_INIT_STS_MASK		(1 << TIMER_TIMER1_INIT_STS_SHIFT)
#define TIMER_TIMER0_INIT_STS_MASK		(1 << TIMER_TIMER0_INIT_STS_SHIFT)

#define TIMER_TIMER4_INIT_EN_SHIFT		4
#define TIMER_TIMER3_INIT_EN_SHIFT		3
#define TIMER_TIMER2_INIT_EN_SHIFT		2
#define TIMER_TIMER1_INIT_EN_SHIFT		1
#define TIMER_TIMER0_INIT_EN_SHIFT		0

#define TIMER_TIMER4_INIT_EN_MASK		(1 << TIMER_TIMER4_INIT_EN_SHIFT)
#define TIMER_TIMER3_INIT_EN_MASK		(1 << TIMER_TIMER3_INIT_EN_SHIFT)
#define TIMER_TIMER2_INIT_EN_MASK		(1 << TIMER_TIMER2_INIT_EN_SHIFT)
#define TIMER_TIMER1_INIT_EN_MASK		(1 << TIMER_TIMER1_INIT_EN_SHIFT)
#define TIMER_TIMER0_INIT_EN_MASK		(1 << TIMER_TIMER0_INIT_EN_SHIFT)


/* macro */
#define TIMER_EXT_VAL(reg, REG_FIELD)    (((reg) & TIMER_##REG_FIELD##_MASK) >> TIMER_##REG_FIELD##_SHIFT)
#define TIMER_SET_VAL(REG_FIELD, val)	(((val) << TIMER_##REG_FIELD##_SHIFT) & TIMER_##REG_FIELD##_MASK)
#define TIMER_INST_VAL(reg, REG_FIELD, val)	((reg) = ((reg) & ~ TIMER_##REG_FIELD##_MASK) | TIMER_SET_VAL(REG_FIELD, val))



#endif /* TIMER_H_ */
